#######################################################
#        This is a YAML-formatted file.               #
# Declare variables to be passed into your templates. #
#      Default values for bbilkevych-chart.            #
#######################################################
namespace: bbilkevych
email: borysbilkevych@gmail.com

##############
# Deployment #
##############

#Scalability for different situations#
replicaCount: 2

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

#Strategy for Deployment#
strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1
  type: RollingUpdate

#Image for pods#
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

#Probes#
livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: 80
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
  initialDelaySeconds: 10

readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: 80
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
  initialDelaySeconds: 10

#Container Port#
container_port: 80

#Resources#
resources:
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 50m
    memory: 50Mi


###########
# Service #
###########

service:
  type: ClusterIP
  port: 80
  
ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http

#################
# Ingress nginx #
#################
# ingress:
#   enabled: true
#   className: ""
#   annotations:
#      kubernetes.io/ingress.class: "nginx"
#   hosts:
#     - host: hw9-bbilkevych.students.java-academy.xyz
#       paths:
#         - path: /
#           pathType: Prefix
#           backend:
#             service:
#               name: "service-name"
#               port:
#                 number: 80
#   tls: []

###################################
# Ingress/Bonus Point (nginx-ssl) #
###################################
clusterissuer: letsencrypt-stage

# basic-auth
auth:
  nginx.ingress.kubernetes.io/auth-type: basic
  nginx.ingress.kubernetes.io/auth-secret: basic-auth
  nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - bbilkevych'

# main ingress
ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: "nginx-ssl"
    cert-manager.io/issuer: letsencrypt-stage
  hosts:
    - host: <your_host_name>
      paths:
        - path: /
          pathType: Prefix
  tls:
  - hosts:
    - <your_host_name>
    secretName: bbilkevych-cert-tls

##########
# Issuer #
##########
class: nginx-ssl

########
# Test #
########
test:
  "helm.sh/hook": test
  "helm.sh/hook-delete-policy": hook-succeeded