apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bbilkevych-chart.fullname" . }}
  labels:
    {{- include "bbilkevych-chart.labels" . | nindent 4 }}
spec:
  {{- if not $.Values.autoscaling.enabled }}
  replicas: {{ $.Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bbilkevych-chart.selectorLabels" . | nindent 6 }}
  strategy:
    {{- toYaml $.Values.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "bbilkevych-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          name: {{ $.Chart.Name }}
          ports:
            - containerPort: {{ $.Values.container_port }}
          livenessProbe:
            {{- toYaml $.Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml $.Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}