apiVersion: v1
kind: Service
metadata:
  name: {{ include "bbilkevych-chart.fullname" . }}
  labels:
    {{- include "bbilkevych-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.ports }}
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "bbilkevych-chart.selectorLabels" . | nindent 4 }}